---
kind: pipeline
name: ci
steps:
- name: test
  image: node:10.16.0-alpine
  commands:
  - yarn install
  - yarn test

- name: build
  image: node:10.16.0-alpine
  commands:
  - yarn build

- name: docker-publish-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: "jjbubudi/tides-web"
    tag: "${DRONE_TAG}-amd64"
    build_args:
    - BASE_IMAGE=amd64/nginx:1.16.0-alpine
  when:
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: docker-publish-arm64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: "jjbubudi/tides-web"
    tag: "${DRONE_TAG}-arm64"
    build_args:
    - BASE_IMAGE=arm64v8/nginx:1.16.0-alpine
  when:
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: docker-publish-arm
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: "jjbubudi/tides-web"
    tag: "${DRONE_TAG}-arm"
    build_args:
    - BASE_IMAGE=arm32v7/nginx:1.16.0
  when:
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

---
kind: pipeline
name: manifest
steps:
- name: manifest
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
    target: "jjbubudi/tides-web:${DRONE_TAG}"
    template: "jjbubudi/tides-web:${DRONE_TAG}-ARCH"
  when:
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

depends_on:
- ci